/**
  ******************************************************************************
  * @file    dma_config.c
  * @brief   DMA Configuration Implementation for Autonomous Sensor Reading
  * @date    December 22, 2025
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "dma_config.h"
#include "sensor_scheduler.h"
#include "main.h"
#include "sensor_server.h"
#include <string.h>
#include <stdio.h>

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/

/* DMA handles */
DMA_HandleTypeDef hdma_i2c1_tx;
DMA_HandleTypeDef hdma_i2c1_rx;
DMA_HandleTypeDef hdma_i2c2_tx;
DMA_HandleTypeDef hdma_i2c2_rx;
DMA_HandleTypeDef hdma_mem2mem;

/* Sensor DMA contexts */
DMA_SensorContext_t sensorContexts[SENSOR_COUNT];

/* Error statistics */
static uint32_t errorCount[SENSOR_COUNT] = {0};
static uint32_t timeoutCount[SENSOR_COUNT] = {0};

/* Raw data buffers (DMA destination) */
static uint8_t bmi270_raw_buffer[12];      // 6 axes × 2 bytes
static uint8_t mvh4000d_raw_buffer[4];     // 2 sensors × 2 bytes
static uint8_t lps22hh_raw_buffer[3];      // 24-bit pressure
static uint8_t zmod4510_raw_buffer[7];     // AQI data
static uint8_t gnss_raw_buffer[20];        // Full PVT data

/* BLE packet buffers (formatted for notification) */
static uint8_t ble_bmi270_gyro_packet[12];    // Gyro X, Y, Z (2 bytes each × 3 axes × 2 for both)
static uint8_t ble_bmi270_accel_packet[12];   // Accel X, Y, Z
static uint8_t ble_mvh4000d_temp_packet[2];   // Temperature
static uint8_t ble_mvh4000d_hum_packet[2];    // Humidity
static uint8_t ble_lps22hh_press_packet[4];   // Pressure (converted to 4 bytes)
static uint8_t ble_zmod4510_aqi_packet[7];    // AQI data
static uint8_t ble_gnss_packet[20];           // GPS data

/* External variables --------------------------------------------------------*/
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;

/* Private function prototypes -----------------------------------------------*/
static HAL_StatusTypeDef DMA_ConfigureChannel(DMA_HandleTypeDef *hdma, 
                                               uint32_t request,
                                               uint32_t direction,
                                               uint32_t periph_addr,
                                               uint32_t mem_addr,
                                               uint32_t data_length,
                                               uint32_t priority);
static void DMA_InitSensorContext(SensorID_t sensor);
static void DMA_InitAllSensorContexts(void);
static SensorID_t DMA_GetSensorFromHandle(DMA_HandleTypeDef *hdma);

/* Exported functions --------------------------------------------------------*/

/**
  * @brief  Initialize all DMA channels for autonomous operation
  * @note   STM32WB07-specific DMA initialization generated by CubeMX
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_AutonomousSystem_Init(void)
{
    /* Enable DMA controller clock */
    __HAL_RCC_DMA_CLK_ENABLE();

    /* DMA interrupt init */
    /* DMA_IRQn interrupt configuration */
    HAL_NVIC_SetPriority(DMA_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(DMA_IRQn);
    
    /* Initialize sensor contexts for all sensors */
    DMA_InitAllSensorContexts();
    
    /* NOTE: DMA-to-I2C linking happens in HAL_I2C_MspInit() */
    /* DMA handles are configured when I2C peripherals are initialized */
    
    return HAL_OK;
}

/**
  * @brief  Legacy MX_DMA_Init function for compatibility
  * @note   Calls DMA_AutonomousSystem_Init()
  */
HAL_StatusTypeDef MX_DMA_Init(void)
{
    return DMA_AutonomousSystem_Init();
}

/**
  * @brief  Initialize sensor contexts for autonomous DMA operation
  * @note   Called internally after DMA init
  * @retval None
  */
static void DMA_InitAllSensorContexts(void)
{
    DMA_InitSensorContext(SENSOR_BMI270);
    DMA_InitSensorContext(SENSOR_MVH4000D);
    DMA_InitSensorContext(SENSOR_LPS22HH);
    DMA_InitSensorContext(SENSOR_ZMOD4510);
    DMA_InitSensorContext(SENSOR_GNSS);
}

/**
  * @brief  De-initialize DMA system
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_AutonomousSystem_DeInit(void)
{
    HAL_DMA_DeInit(&hdma_i2c1_tx);
    HAL_DMA_DeInit(&hdma_i2c1_rx);
    HAL_DMA_DeInit(&hdma_i2c2_tx);
    HAL_DMA_DeInit(&hdma_i2c2_rx);
    HAL_DMA_DeInit(&hdma_mem2mem);
    
    return HAL_OK;
}

/**
  * @brief  Start autonomous sensor read via DMA
  * @param  sensor: Sensor ID
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_Sensor_StartRead(SensorID_t sensor)
{
    HAL_StatusTypeDef status;
    DMA_SensorContext_t *ctx = &sensorContexts[sensor];
    
    /* Check if sensor is enabled before starting */
    extern uint8_t Scheduler_IsSensorEnabled(SensorID_t sensor);
    if (!Scheduler_IsSensorEnabled(sensor)) {
        return HAL_ERROR;  // Don't start DMA for disabled sensors
    }
    
    /* Check if previous transfer is still busy */
    if (ctx->state == DMA_TRANSFER_BUSY) {
        return HAL_BUSY;
    }
    
    /* Update state (allow retry even if previous was error) */
    ctx->state = DMA_TRANSFER_BUSY;
    ctx->startTime = HAL_GetTick();
    
    /* Start I2C read with DMA */
    status = HAL_I2C_Mem_Read_DMA(ctx->hi2c, 
                                   ctx->devAddr, 
                                   ctx->regAddr, 
                                   I2C_MEMADD_SIZE_8BIT,
                                   ctx->pRawData, 
                                   ctx->dataSize);
    
    if (status != HAL_OK) {
        ctx->state = DMA_TRANSFER_IDLE;  // Reset to IDLE for next attempt
        errorCount[sensor]++;
        printf("[DMA-ERR] S%d start failed: %d\r\n", sensor, status);
        return status;
    }
    
    return HAL_OK;
}

/**
  * @brief  Abort sensor DMA transfer
  * @param  sensor: Sensor ID
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_Sensor_AbortRead(SensorID_t sensor)
{
    DMA_SensorContext_t *ctx = &sensorContexts[sensor];
    
    HAL_I2C_Master_Abort_IT(ctx->hi2c, ctx->devAddr);
    ctx->state = DMA_TRANSFER_IDLE;
    
    return HAL_OK;
}

/**
  * @brief  Check if sensor data is ready
  * @param  sensor: Sensor ID
  * @retval 1 if ready, 0 if not ready
  */
uint8_t DMA_Sensor_IsDataReady(SensorID_t sensor)
{
    return (sensorContexts[sensor].state == DMA_TRANSFER_COMPLETE);
}

/**
  * @brief  Get sensor DMA context
  * @param  sensor: Sensor ID
  * @retval Pointer to DMA context
  */
DMA_SensorContext_t* DMA_Sensor_GetContext(SensorID_t sensor)
{
    return &sensorContexts[sensor];
}

/**
  * @brief  Format raw sensor data to BLE packet (via DMA Mem2Mem)
  * @param  sensor: Sensor ID
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_FormatToBLEPacket(SensorID_t sensor)
{
    DMA_SensorContext_t *ctx = &sensorContexts[sensor];
    
    /* For most sensors, raw data is already in correct format */
    /* Just copy via DMA Mem2Mem */
    return HAL_DMA_Start(&hdma_mem2mem,
                         (uint32_t)ctx->pRawData,
                         (uint32_t)ctx->pBlePacket,
                         ctx->dataSize);
}

/**
  * @brief  DMA transfer complete callback
  * @param  hdma: DMA handle
  * @retval None
  */
void DMA_TransferComplete_Callback(DMA_HandleTypeDef *hdma)
{
    SensorID_t sensor = DMA_GetSensorFromHandle(hdma);
    
    if (sensor < SENSOR_COUNT) {
        DMA_SensorContext_t *ctx = &sensorContexts[sensor];
        ctx->state = DMA_TRANSFER_COMPLETE;
        
        /* Automatically format to BLE packet */
        DMA_FormatToBLEPacket(sensor);
    }
}

/**
  * @brief  DMA transfer error callback
  * @param  hdma: DMA handle
  * @retval None
  */
void DMA_TransferError_Callback(DMA_HandleTypeDef *hdma)
{
    SensorID_t sensor = DMA_GetSensorFromHandle(hdma);
    
    if (sensor < SENSOR_COUNT) {
        DMA_SensorContext_t *ctx = &sensorContexts[sensor];
        ctx->state = DMA_TRANSFER_ERROR;
        errorCount[sensor]++;
        
        /* Check if sensor is still enabled before auto-retry */
        extern uint8_t Scheduler_IsSensorEnabled(SensorID_t sensor);
        if (!Scheduler_IsSensorEnabled(sensor)) {
            printf("[DMA] Sensor %d disabled, not retrying\r\n", sensor);
            ctx->retryCount = 0;
            ctx->state = DMA_TRANSFER_IDLE;
            return;
        }
        
        /* Auto-retry if not exceeded max retries */
        if (ctx->retryCount < DMA_MAX_RETRIES) {
            ctx->retryCount++;
            DMA_Sensor_StartRead(sensor);
        } else {
            ctx->retryCount = 0;
        }
    }
}

/**
  * @brief  Monitor DMA timeouts (call from scheduler)
  * @retval None
  */
void DMA_CheckTimeouts(void)
{
    uint32_t now = HAL_GetTick();
    
    for (uint8_t i = 0; i < SENSOR_COUNT; i++) {
        DMA_SensorContext_t *ctx = &sensorContexts[i];
        
        if (ctx->state == DMA_TRANSFER_BUSY) {
            if ((now - ctx->startTime) > ctx->timeout) {
                ctx->state = DMA_TRANSFER_TIMEOUT;
                timeoutCount[i]++;
                DMA_ResetChannel((SensorID_t)i);
            }
        }
    }
}

/**
  * @brief  Reset DMA channel and I2C peripheral
  * @param  sensor: Sensor ID
  * @retval None
  */
void DMA_ResetChannel(SensorID_t sensor)
{
    DMA_SensorContext_t *ctx = &sensorContexts[sensor];
    
    /* Abort DMA transfer */
    HAL_DMA_Abort(ctx->hi2c->hdmarx);
    HAL_DMA_Abort(ctx->hi2c->hdmatx);
    
    /* Reset I2C peripheral */
    if (ctx->hi2c == &hi2c1) {
        __HAL_RCC_I2C1_FORCE_RESET();
        HAL_Delay(1);
        __HAL_RCC_I2C1_RELEASE_RESET();
    } else if (ctx->hi2c == &hi2c2) {
        __HAL_RCC_I2C2_FORCE_RESET();
        HAL_Delay(1);
        __HAL_RCC_I2C2_RELEASE_RESET();
    }
    
    /* Re-initialize I2C */
    HAL_I2C_Init(ctx->hi2c);
    
    /* Reset context */
    ctx->state = DMA_TRANSFER_IDLE;
    ctx->retryCount = 0;
}

/**
  * @brief  Get DMA error statistics
  */
void DMA_GetErrorStats(SensorID_t sensor, uint32_t *pErrorCount, uint32_t *pTimeoutCount)
{
    if (pErrorCount) *pErrorCount = errorCount[sensor];
    if (pTimeoutCount) *pTimeoutCount = timeoutCount[sensor];
}

/* Private functions ---------------------------------------------------------*/

/**
  * @brief  Initialize sensor DMA context
  * @param  sensor: Sensor ID
  * @retval None
  */
static void DMA_InitSensorContext(SensorID_t sensor)
{
    DMA_SensorContext_t *ctx = &sensorContexts[sensor];
    
    ctx->state = DMA_TRANSFER_IDLE;
    ctx->retryCount = 0;
    
    switch (sensor) {
        case SENSOR_BMI270:
            ctx->hi2c = &hi2c2;
            ctx->devAddr = 0x68 << 1;
            ctx->regAddr = 0x0C;  // Gyro/Accel data register
            ctx->pRawData = bmi270_raw_buffer;
            ctx->pBlePacket = ble_bmi270_gyro_packet;  // Will format both gyro and accel
            ctx->dataSize = 12;
            ctx->timeout = DMA_TIMEOUT_BMI270;
            break;
            
        case SENSOR_MVH4000D:
            ctx->hi2c = &hi2c2;
            ctx->devAddr = 0xA8;  // Already shifted in sensor init
            ctx->regAddr = 0x00;
            ctx->pRawData = mvh4000d_raw_buffer;
            ctx->pBlePacket = ble_mvh4000d_temp_packet;
            ctx->dataSize = 4;
            ctx->timeout = DMA_TIMEOUT_MVH4000D;
            break;
            
        case SENSOR_LPS22HH:
            ctx->hi2c = &hi2c2;
            ctx->devAddr = 0xB8;  // Already shifted in sensor init
            ctx->regAddr = 0x28;  // Pressure data register
            ctx->pRawData = lps22hh_raw_buffer;
            ctx->pBlePacket = ble_lps22hh_press_packet;
            ctx->dataSize = 3;
            ctx->timeout = DMA_TIMEOUT_LPS22HH;
            break;
            
        case SENSOR_ZMOD4510:
            ctx->hi2c = &hi2c1;
            ctx->devAddr = 0x32 << 1;
            ctx->regAddr = 0x00;
            ctx->pRawData = zmod4510_raw_buffer;
            ctx->pBlePacket = ble_zmod4510_aqi_packet;
            ctx->dataSize = 7;
            ctx->timeout = DMA_TIMEOUT_ZMOD4510;
            break;
            
        case SENSOR_GNSS:
            ctx->hi2c = &hi2c1;
            ctx->devAddr = 0x42 << 1;
            ctx->regAddr = 0xFF;  // GNSS uses special protocol
            ctx->pRawData = gnss_raw_buffer;
            ctx->pBlePacket = ble_gnss_packet;
            ctx->dataSize = 20;
            ctx->timeout = DMA_TIMEOUT_GNSS;
            break;
            
        default:
            break;
    }
}

/**
  * @brief  Get sensor ID from DMA handle
  * @param  hdma: DMA handle
  * @retval Sensor ID or SENSOR_COUNT if not found
  */
static SensorID_t DMA_GetSensorFromHandle(DMA_HandleTypeDef *hdma)
{
    extern uint8_t Scheduler_IsSensorEnabled(SensorID_t sensor);
    
    for (uint8_t i = 0; i < SENSOR_COUNT; i++) {
        /* Skip disabled sensors in lookup */
        if (!Scheduler_IsSensorEnabled((SensorID_t)i)) {
            continue;
        }
        
        if (sensorContexts[i].hi2c->hdmarx == hdma) {
            return (SensorID_t)i;
        }
    }
    return SENSOR_COUNT;
}

/**
  * @brief  HAL I2C Memory Read Complete Callback (called when DMA transfer completes)
  * @param  hi2c: I2C handle
  * @retval None
  * @note DISABLED - Using simplified MVH4000D DMA instead
  */
#if 0  // Disabled for MVH4000D DMA test
void HAL_I2C_MemRxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    printf("[DMA-CB] I2C RX Complete! hi2c=%p, hdmarx=%p\r\n", hi2c, hi2c->hdmarx);
    
    /* Find which sensor completed */
    SensorID_t sensor = DMA_GetSensorFromHandle(hi2c->hdmarx);
    
    printf("[DMA-CB] Sensor ID: %d\r\n", sensor);
    
    if (sensor < SENSOR_COUNT) {
        DMA_SensorContext_t *ctx = &sensorContexts[sensor];
        
        /* Update state */
        ctx->state = DMA_TRANSFER_COMPLETE;
        
        /* Calculate transfer time */
        uint32_t elapsed = HAL_GetTick() - ctx->startTime;
        
        /* Update scheduler statistics */
        extern SchedulerStats_t schedulerStats;
        schedulerStats.successfulReads[sensor]++;
        schedulerStats.averageReadTime[sensor] = 
            ((schedulerStats.averageReadTime[sensor] * (schedulerStats.successfulReads[sensor] - 1)) + elapsed) / 
            schedulerStats.successfulReads[sensor];
        
        /* Copy raw data to BLE packet */
        memcpy(ctx->pBlePacket, ctx->pRawData, ctx->dataSize);
        
        /* Send BLE notification immediately */
        SENSOR_SERVER_Data_t notification_data;
        notification_data.p_Payload = ctx->pBlePacket;
        notification_data.Length = ctx->dataSize;
        
        switch (sensor) {
            case SENSOR_BMI270:
                /* BMI270 has both gyro and acc - send gyro for now */
                SENSOR_SERVER_UpdateValue(SENSOR_SERVER_GYRO_CHAR, &notification_data);
                break;
            case SENSOR_MVH4000D:
                /* MVH4000D has temp+humidity - send temp for now */
                SENSOR_SERVER_UpdateValue(SENSOR_SERVER_TEMP_CHAR, &notification_data);
                break;
            case SENSOR_LPS22HH:
                SENSOR_SERVER_UpdateValue(SENSOR_SERVER_PRS_CHAR, &notification_data);
                break;
            case SENSOR_ZMOD4510:
                SENSOR_SERVER_UpdateValue(SENSOR_SERVER_AQI_CHAR, &notification_data);
                break;
            case SENSOR_GNSS:
                SENSOR_SERVER_UpdateValue(SENSOR_SERVER_GNSS_CHAR, &notification_data);
                break;
            default:
                break;
        }
    }
}
#endif  // End of disabled HAL_I2C_MemRxCpltCallback

/**
  * @brief  HAL I2C Error Callback
  * @param  hi2c: I2C handle
  * @retval None
  * @note DISABLED - Using simplified MVH4000D DMA instead
  */
#if 0  // Disabled for MVH4000D DMA test
void HAL_I2C_ErrorCallback(I2C_HandleTypeDef *hi2c)
{
    /* Find which sensor had error */
    SensorID_t sensor = DMA_GetSensorFromHandle(hi2c->hdmarx);
    
    if (sensor < SENSOR_COUNT) {
        DMA_SensorContext_t *ctx = &sensorContexts[sensor];
        
        /* Check if sensor is still enabled */
        extern uint8_t Scheduler_IsSensorEnabled(SensorID_t sensor);
        if (!Scheduler_IsSensorEnabled(sensor)) {
            /* Sensor disabled - don't log error, just reset state */
            ctx->state = DMA_TRANSFER_IDLE;
            ctx->retryCount = 0;
            return;
        }
        
        /* Log I2C error for debugging */
        uint32_t i2c_error = HAL_I2C_GetError(hi2c);
        if (i2c_error != HAL_I2C_ERROR_NONE) {
            printf("[DMA-ERR] S%d I2C error: 0x%08lX\r\n", sensor, i2c_error);
        }
        
        /* Reset state to IDLE so next read can proceed */
        ctx->state = DMA_TRANSFER_IDLE;
        errorCount[sensor]++;
    }
}
#endif  // End of disabled HAL_I2C_ErrorCallback

/* NOTE: DMA_IRQHandler is now in stm32wb0x_it.c (STM32WB07 standard location) */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
