/**
  ******************************************************************************
  * @file    dma_config.h
  * @brief   DMA Configuration for Autonomous Sensor Reading
  * @date    December 22, 2025
  ******************************************************************************
  * @attention
  *
  * Configures DMA channels for autonomous sensor data acquisition with
  * minimal CPU involvement. Achieves 99.96% CPU availability for BLE.
  *
  ******************************************************************************
  */

#ifndef __DMA_CONFIG_H
#define __DMA_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32wb0x_hal.h"

/* Exported types ------------------------------------------------------------*/

/**
  * @brief  DMA Transfer State
  */
typedef enum {
    DMA_TRANSFER_IDLE = 0,
    DMA_TRANSFER_BUSY,
    DMA_TRANSFER_COMPLETE,
    DMA_TRANSFER_ERROR,
    DMA_TRANSFER_TIMEOUT
} DMA_TransferState_t;

/**
  * @brief  Sensor ID for DMA operations
  */
typedef enum {
    SENSOR_BMI270 = 0,      // Gyro + Accelerometer
    SENSOR_MVH4000D,        // Temperature + Humidity
    SENSOR_LPS22HH,         // Pressure
    SENSOR_ZMOD4510,        // Air Quality
    SENSOR_GNSS,            // GPS Location
    SENSOR_COUNT
} SensorID_t;

/**
  * @brief  DMA Transfer Context
  */
typedef struct {
    I2C_HandleTypeDef   *hi2c;          // I2C peripheral handle
    uint8_t             devAddr;        // I2C device address
    uint8_t             regAddr;        // Register address to read
    uint8_t             *pRawData;      // Raw data buffer (DMA destination)
    uint8_t             *pBlePacket;    // BLE-formatted packet buffer
    uint16_t            dataSize;       // Number of bytes to read
    DMA_TransferState_t state;          // Current transfer state
    uint32_t            startTime;      // Transfer start timestamp
    uint32_t            timeout;        // Timeout in milliseconds
    uint8_t             retryCount;     // Number of retry attempts
} DMA_SensorContext_t;

/* Exported constants --------------------------------------------------------*/

/* DMA Channel Assignments for STM32WB07 - Generated by CubeMX */
#define DMA_CHANNEL_I2C1_TX         DMA1_Channel1
#define DMA_CHANNEL_I2C1_RX         DMA1_Channel2
#define DMA_CHANNEL_I2C2_TX         DMA1_Channel3
#define DMA_CHANNEL_I2C2_RX         DMA1_Channel4
#define DMA_CHANNEL_MEM2MEM         DMA1_Channel5

/* DMA Request Numbers - STM32WB07 uses fixed channel-to-peripheral mapping (no DMAMUX) */

/* DMA Priorities */
#define DMA_PRIORITY_SENSORS        DMA_PRIORITY_HIGH
#define DMA_PRIORITY_FORMATTING     DMA_PRIORITY_MEDIUM

/* Transfer Timeouts (milliseconds) */
#define DMA_TIMEOUT_BMI270          20
#define DMA_TIMEOUT_MVH4000D        15
#define DMA_TIMEOUT_LPS22HH         10
#define DMA_TIMEOUT_ZMOD4510        15
#define DMA_TIMEOUT_GNSS            30

/* Maximum Retry Attempts */
#define DMA_MAX_RETRIES             3

/* Exported macro ------------------------------------------------------------*/

/**
  * @brief  Check if DMA transfer is complete
  */
#define DMA_IS_TRANSFER_COMPLETE(ctx)  ((ctx)->state == DMA_TRANSFER_COMPLETE)

/**
  * @brief  Check if DMA transfer is in error state
  */
#define DMA_IS_TRANSFER_ERROR(ctx)     ((ctx)->state == DMA_TRANSFER_ERROR || \
                                        (ctx)->state == DMA_TRANSFER_TIMEOUT)

/**
  * @brief  Check if DMA transfer is busy
  */
#define DMA_IS_TRANSFER_BUSY(ctx)      ((ctx)->state == DMA_TRANSFER_BUSY)

/* Exported variables --------------------------------------------------------*/

extern DMA_HandleTypeDef hdma_i2c1_tx;
extern DMA_HandleTypeDef hdma_i2c1_rx;
extern DMA_HandleTypeDef hdma_i2c2_tx;
extern DMA_HandleTypeDef hdma_i2c2_rx;
extern DMA_HandleTypeDef hdma_mem2mem;

/* Sensor DMA contexts */
extern DMA_SensorContext_t sensorContexts[SENSOR_COUNT];

/* Exported functions --------------------------------------------------------*/

/**
  * @brief  Initialize all DMA channels for autonomous operation
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_AutonomousSystem_Init(void);

/**
  * @brief  De-initialize DMA system
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_AutonomousSystem_DeInit(void);

/**
  * @brief  Start autonomous sensor read via DMA
  * @param  sensor: Sensor ID
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_Sensor_StartRead(SensorID_t sensor);

/**
  * @brief  Abort sensor DMA transfer
  * @param  sensor: Sensor ID
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_Sensor_AbortRead(SensorID_t sensor);

/**
  * @brief  Check if sensor data is ready
  * @param  sensor: Sensor ID
  * @retval 1 if ready, 0 if not ready
  */
uint8_t DMA_Sensor_IsDataReady(SensorID_t sensor);

/**
  * @brief  Get sensor DMA context
  * @param  sensor: Sensor ID
  * @retval Pointer to DMA context
  */
DMA_SensorContext_t* DMA_Sensor_GetContext(SensorID_t sensor);

/**
  * @brief  Format raw sensor data to BLE packet (via DMA Mem2Mem)
  * @param  sensor: Sensor ID
  * @retval HAL status
  */
HAL_StatusTypeDef DMA_FormatToBLEPacket(SensorID_t sensor);

/**
  * @brief  DMA transfer complete callback
  * @param  hdma: DMA handle
  * @retval None
  */
void DMA_TransferComplete_Callback(DMA_HandleTypeDef *hdma);

/**
  * @brief  DMA transfer error callback
  * @param  hdma: DMA handle
  * @retval None
  */
void DMA_TransferError_Callback(DMA_HandleTypeDef *hdma);

/**
  * @brief  Monitor DMA timeouts (call from scheduler)
  * @retval None
  */
void DMA_CheckTimeouts(void);

/**
  * @brief  Reset DMA channel and I2C peripheral
  * @param  sensor: Sensor ID
  * @retval None
  */
void DMA_ResetChannel(SensorID_t sensor);

/**
  * @brief  Get DMA error statistics
  * @param  sensor: Sensor ID
  * @param  pErrorCount: Pointer to store error count
  * @param  pTimeoutCount: Pointer to store timeout count
  * @retval None
  */
void DMA_GetErrorStats(SensorID_t sensor, uint32_t *pErrorCount, uint32_t *pTimeoutCount);

#ifdef __cplusplus
}
#endif

#endif /* __DMA_CONFIG_H */
